# Todo! Parameterize this.
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: media-nfs-class
provisioner: cluster.local/nfs-subdir-external-provisioner
parameters:
  readOnly: "false"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-pv
spec:
  capacity:
    storage: 10Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: media-nfs-class
  nfs:
    server: "file.infra.bergermeister.at"
    path: "/mnt/dev-data1/media-dev/"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: media-nfs-class
  resources:
    requests:
      storage: 10Ti
