apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ombi
  labels:
    app: ombi
spec:
  serviceName: ombi-headless
  # progressDeadlineSeconds: 600
  replicas: 1
  # strategy:
  #   type: Recreate
  selector:
    matchLabels:
      app: ombi
  template:
    metadata:
      labels:
        app: ombi
    spec:
      containers:
      - name: ombi
        image: ghcr.io/linuxserver/ombi:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3579
          name: http-tcp
          protocol: TCP
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "CEST"
        - name: BASE_URL
          value: "/ombi"
        volumeMounts:
        - name: ombi-config
          mountPath: /config
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: ombi-config
        persistentVolumeClaim:
          claimName: ombi-config
      # securityContext:
      #   runAsUser: 1000
      #   runAsGroup: 1000
      #   fsGroup: 1000
---
apiVersion: v1
kind: Service
metadata:
  name: ombi-headless
spec:
  clusterIP: None
  selector:
    app: ombi
  ports:
  - protocol: TCP
    port: 3579
    targetPort: 3579
---
apiVersion: v1
kind: Service
metadata:
  name: ombi-service
spec:
  selector:
    app: ombi
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3579
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ombi-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
spec:
  ingressClassName: nginx
  rules:
  - host: ombi.burglarr.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ombi-service
            port:
              number: 80
